name: TV-Multiplatform Build
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
env:
  tag: ${{ github.ref_name != '' && github.ref_name || github.run_id }}
jobs:
            #            https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Signing_and_notarization_on_macOS/README.md
  build-mac:
    runs-on: macos-13
    steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: 17
           cache: 'gradle'
       - run: ls
       - run: chmod +x ./gradlew && ./gradlew createReleaseDistributable
       - run: ./gradlew notarizedmg
       - run: ls
       - name: compress
         run: zip -q -r ./TV-mac-$tag.zip ./composeApp/build/compose/binaries/main-release/app
       - name: move file
         run: mv ./composeApp/build/compose/binaries/main-release/dmg/*.dmg ./TV-mac-$tag.dmg
       - run: ls
       - uses: actions/upload-artifact@v4
         with:
           name: mac-file
           path: |
             *.dmg
             *.zip
  release:
    runs-on: ubuntu-latest
    needs: [ build-mac]
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - run: ls && tree
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.zip
            **/*.deb
            **/*.pkg
            **/*.dmg
            **/*.msi
          tag_name: 1.1.1
    permissions:
      contents: write
